In [2]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-03-2020.csv')
df.head(10)

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-03 22:46:37,34.223334,-82.461707,6,0,0,0,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-03 22:46:37,30.295065,-92.414197,72,1,0,0,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-03 22:46:37,37.767072,-75.632346,8,0,0,0,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-03 22:46:37,43.452658,-116.241552,307,3,0,0,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-03 22:46:37,41.330756,-94.471059,1,0,0,0,"Adair, Iowa, US"
5,29001.0,Adair,Missouri,US,2020-04-03 22:46:37,40.190586,-92.600782,6,0,0,0,"Adair, Missouri, US"
6,40001.0,Adair,Oklahoma,US,2020-04-03 22:46:37,35.884942,-94.658593,14,0,0,0,"Adair, Oklahoma, US"
7,8001.0,Adams,Colorado,US,2020-04-03 22:46:37,39.874321,-104.336258,260,7,0,0,"Adams, Colorado, US"
8,16003.0,Adams,Idaho,US,2020-04-03 22:46:37,44.893336,-116.454525,1,0,0,0,"Adams, Idaho, US"
9,17001.0,Adams,Illinois,US,2020-04-03 22:46:37,39.988156,-91.187868,2,0,0,0,"Adams, Illinois, US"

In [ ]:
df.shape

In [3]:
#04/02: 2312, 12
usa = df[df['Country_Region'] == 'US']
usa.shape

(2368, 12)

In [4]:
#04/02 243453
#04/03 275586
usa.groupby('Country_Region')['Confirmed'].sum()

Country_Region
US    275586
Name: Confirmed, dtype: int64

In [5]:
#04/02 5926
#04/03 7087
usa.groupby('Country_Region')['Deaths'].sum()

Country_Region
US    7087
Name: Deaths, dtype: int64

In [6]:
#04/02, confirmed 826, deaths 21
#04/02, confirmed 899, deaths 22
usa[usa['Province_State'] == 'Oregon'].groupby('Province_State')['Confirmed','Deaths'].sum()

                Confirmed  Deaths
Province_State
Oregon                899      22

In [102]:
usa[usa['Province_State'] == 'Oregon'].groupby('Province_State')['Deaths'].sum()

Province_State
Oregon    21
Name: Deaths, dtype: int64

In [6]:
usa[usa['Province_State'] == 'Oregon']

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
118,41001.0,Baker,Oregon,US,2020-03-30 22:52:45,44.709156,-117.674988,0,0,0,0,"Baker, Oregon, US"
186,41003.0,Benton,Oregon,US,2020-03-30 22:52:45,44.491673,-123.431699,9,0,0,0,"Benton, Oregon, US"
512,41005.0,Clackamas,Oregon,US,2020-03-30 22:52:45,45.187874,-122.217963,40,3,0,0,"Clackamas, Oregon, US"
537,41007.0,Clatsop,Oregon,US,2020-03-30 22:52:45,45.997129,-123.660711,3,0,0,0,"Clatsop, Oregon, US"
609,41009.0,Columbia,Oregon,US,2020-03-30 22:52:45,45.944643,-123.089090,1,0,0,0,"Columbia, Oregon, US"
633,41011.0,Coos,Oregon,US,2020-03-30 22:52:45,43.174069,-124.059451,0,0,0,0,"Coos, Oregon, US"
673,41013.0,Crook,Oregon,US,2020-03-30 22:52:45,44.142302,-120.356297,0,0,0,0,"Crook, Oregon, US"
693,41015.0,Curry,Oregon,US,2020-03-30 22:52:45,42.459113,-124.157282,0,0,0,0,"Curry, Oregon, US"
771,41017.0,Deschutes,Oregon,US,2020-03-30 22:52:45,43.915702,-121.228912,25,0,0,0,"Deschutes, Oregon, US"
814,41019.0,Douglas,Oregon,US,2020-03-30 22:52:45,43.279413,-123.167291,8,0,0,0,"Douglas, Oregon, US"
1042,41021.0,Gilliam,Oregon,US,2020-03-30 22:52:45,45.371601,-120.204887,0,0,0,0,"Gilliam, Oregon, US"
1090,41023.0,Grant,Oregon,US,2020-03-30 22:52:45,44.490245,-119.006863,1,0,0,0,"Grant, Oregon, US"
1207,41025.0,Harney,Oregon,US,2020-03-30 22:52:45,43.064227,-118.966631,0,0,0,0,"Harney, Oregon, US"
1288,41027.0,Hood River,Oregon,US,2020-03-30 22:52:45,45.518728,-121.655204,2,0,0,0,"Hood River, Oregon, US"
1381,41029.0,Jackson,Oregon,US,2020-03-30 22:52:45,42.432011,-122.728931,20,0,0,0,"Jackson, Oregon, US"
1418,41031.0,Jefferson,Oregon,US,2020-03-30 22:52:45,44.628068,-121.178320,0,0,0,0,"Jefferson, Oregon, US"
1457,41033.0,Josephine,Oregon,US,2020-03-30 22:52:45,42.366555,-123.556194,10,0,0,0,"Josephine, Oregon, US"
1522,41035.0,Klamath,Oregon,US,2020-03-30 22:52:45,42.687630,-121.649646,4,0,0,0,"Klamath, Oregon, US"
1570,41037.0,Lake,Oregon,US,2020-03-30 22:52:45,42.792467,-120.385016,0,0,0,0,"Lake, Oregon, US"
1588,41039.0,Lane,Oregon,US,2020-03-30 22:52:45,43.937270,-122.847753,12,1,0,0,"Lane, Oregon, US"
1680,41041.0,Lincoln,Oregon,US,2020-03-30 22:52:45,44.642529,-123.869912,1,0,0,0,"Lincoln, Oregon, US"
1690,41043.0,Linn,Oregon,US,2020-03-30 22:52:45,44.488995,-122.537315,36,2,0,0,"Linn, Oregon, US"
1779,41045.0,Malheur,Oregon,US,2020-03-30 22:52:45,43.193703,-117.622739,0,0,0,0,"Malheur, Oregon, US"
1803,41047.0,Marion,Oregon,US,2020-03-30 22:52:45,44.902879,-122.581512,123,3,0,0,"Marion, Oregon, US"
2021,41049.0,Morrow,Oregon,US,2020-03-30 22:52:45,45.418466,-119.584546,1,0,0,0,"Morrow, Oregon, US"
2029,41051.0,Multnomah,Oregon,US,2020-03-30 22:52:45,45.547480,-122.416935,100,2,0,0,"Multnomah, Oregon, US"
2308,41053.0,Polk,Oregon,US,2020-03-30 22:52:45,44.903228,-123.412889,15,0,0,0,"Polk, Oregon, US"
2609,41055.0,Sherman,Oregon,US,2020-03-30 22:52:45,45.415016,-120.682783,0,0,0,0,"Sherman, Oregon, US"
2798,41057.0,Tillamook,Oregon,US,2020-03-30 22:52:45,45.462487,-123.712066,3,0,0,0,"Tillamook, Oregon, US"
2854,41059.0,Umatilla,Oregon,US,2020-03-30 22:52:45,45.590731,-118.735383,4,0,0,0,"Umatilla, Oregon, US"
2899,41061.0,Union,Oregon,US,2020-03-30 22:52:45,45.309155,-118.006898,1,0,0,0,"Union, Oregon, US"
2954,41063.0,Wallowa,Oregon,US,2020-03-30 22:52:45,45.578941,-117.183538,0,0,0,0,"Wallowa, Oregon, US"
2981,41065.0,Wasco,Oregon,US,2020-03-30 22:52:45,45.162928,-121.167095,5,0,0,0,"Wasco, Oregon, US"
3007,41067.0,Washington,Oregon,US,2020-03-30 22:52:45,45.559727,-123.095526,168,3,0,0,"Washington, Oregon, US"
3069,41069.0,Wheeler,Oregon,US,2020-03-30 22:52:45,44.726982,-120.028143,0,0,0,0,"Wheeler, Oregon, US"
3154,41071.0,Yamhill,Oregon,US,2020-03-30 22:52:45,45.233304,-123.308696,14,2,0,0,"Yamhill, Oregon, US"

In [7]:
usa[usa['Province_State'] == 'Oregon'].groupby(['Province_State'])['Confirmed'].sum()

Province_State
Oregon    606
Name: Confirmed, dtype: int64

In [8]:
usa.groupby(['Province_State'])['Confirmed'].sum()

Province_State
Alabama                       899
Alaska                        114
American Samoa                  0
Arizona                      1157
Arkansas                      473
California                   7138
Colorado                     2311
Connecticut                  2571
Delaware                      264
Diamond Princess               49
District of Columbia          401
Florida                      5473
Georgia                      2808
Grand Princess                103
Guam                           58
Hawaii                        175
Idaho                         340
Illinois                     5056
Indiana                      1786
Iowa                          424
Kansas                        372
Kentucky                      479
Louisiana                    4025
Maine                         275
Maryland                     1413
Massachusetts                5752
Michigan                     6498
Minnesota                     576
Mississippi                   847
Missouri                     1051
Montana                       171
Nebraska                      145
Nevada                       1012
New Hampshire                 314
New Jersey                  16636
New Mexico                    237
New York                    66663
North Carolina               1313
North Dakota                  109
Northern Mariana Islands        0
Ohio                         1933
Oklahoma                      481
Oregon                        606
Pennsylvania                 4155
Puerto Rico                   174
Recovered                       0
Rhode Island                  408
South Carolina                925
South Dakota                  101
Tennessee                    1917
Texas                        3147
Utah                          804
Vermont                       256
Virgin Islands                  0
Virginia                     1020
Washington                   4923
West Virginia                 145
Wisconsin                    1230
Wyoming                        94
Name: Confirmed, dtype: int64

In [9]:
flu = pd.read_csv('/Users/dineshmurali/Documents/FluViewPhase2Data/ILINet.csv')
flu.shape

(1174, 1)

In [10]:
flu.head(10)

                                                                                                                                             PERCENTAGE OF VISITS FOR INFLUENZA-LIKE-ILLNESS REPORTED BY SENTINEL PROVIDERS
REGION TYPE REGION YEAR WEEK % WEIGHTED ILI %UNWEIGHTED ILI AGE 0-4 AGE 25-49 AGE 25-64 AGE 5-24 AGE 50-64 AGE 65 ILITOTAL NUM. OF PROVIDERS                                     TOTAL PATIENTS
National    X      1997 40   1.10148        1.21686         179     X         157       205      X         29     570      192                                                            46842
                        41   1.20007        1.28064         199     X         151       242      X         23     615      191                                                            48023
                        42   1.37876        1.23906         228     X         153       266      X         34     681      219                                                            54961
                        43   1.1992         1.14473         188     X         193       236      X         36     653      213                                                            57044
                        44   1.65618        1.26112         217     X         162       280      X         41     700      213                                                            55506
                        45   1.41326        1.28275         178     X         148       281      X         48     655      195                                                            51062
                        46   1.9868         1.44579         294     X         240       328      X         70     932      248                                                            64463
                        47   2.44749        1.64796         288     X         293       456      X         63     1100     256                                                            66749
                        48   1.73901        1.67517         268     X         206       343      X         69     886      252                                                            52890

In [11]:
fluClin = pd.read_csv('/Users/dineshmurali/Documents/FluViewPhase2Data/WHO_NREVSS_Clinical_Labs.csv')
fluClin.head(10)

                                                                                        *Beginning for the 2015-16 season, reports from public health and clinical laboratories are presented separately in the weekly influenza update, FluView. Data from clinical laboratories include the weekly total number of specimens tested, the number of positive influenza test, and the percent positive by influenza type.
REGION TYPE REGION YEAR WEEK TOTAL SPECIMENS TOTAL A TOTAL B PERCENT POSITIVE PERCENT A                                          PERCENT B
National    X      2015 40   12029           84      43      1.05578          0.698312                                            0.357469
                        41   13111           116     54      1.29662          0.884753                                            0.411868
                        42   13441           97      52      1.10855          0.721672                                            0.386876
                        43   13537           98      52      1.10807          0.723942                                            0.384132
                        44   14687           97      68      1.12344          0.660448                                            0.462994
                        45   15048           122     86      1.38224          0.810739                                            0.571505
                        46   15250           84      98      1.19344          0.55082                                             0.642623
                        47   15234           119     92      1.38506          0.781147                                            0.603912
                        48   16201           145     81      1.39498          0.895006                                            0.499969

In [21]:
#https://gis.cdc.gov/grasp/fluview/FluViewPhase2QuickReferenceGuide.pdf
fluStates = pd.read_csv('/Users/dineshmurali/Documents/FluViewPhase2DataAllStates/ILINet.csv')
fluStates.head(100)

                                                                                                                                                           PERCENTAGE OF VISITS FOR INFLUENZA-LIKE-ILLNESS REPORTED BY SENTINEL PROVIDERS
REGION TYPE REGION               YEAR WEEK % WEIGHTED ILI %UNWEIGHTED ILI AGE 0-4 AGE 25-49 AGE 25-64 AGE 5-24 AGE 50-64 AGE 65 ILITOTAL NUM. OF PROVIDERS                                     TOTAL PATIENTS
States      Alabama              2010 40   X              2.13477         X       X         X         X        X         X      249      35                                                             11664
            Alaska               2010 40   X              0.875146        X       X         X         X        X         X      15       7                                                               1714
            Arizona              2010 40   X              0.674721        X       X         X         X        X         X      172      49                                                             25492
            Arkansas             2010 40   X              0.696056        X       X         X         X        X         X      18       15                                                              2586
            California           2010 40   X              1.95412         X       X         X         X        X         X      632      112                                                            32342
            Colorado             2010 40   X              0.660684        X       X         X         X        X         X      134      14                                                             20282
            Connecticut          2010 40   X              0.0783085       X       X         X         X        X         X      3        12                                                              3831
            Delaware             2010 40   X              0.100125        X       X         X         X        X         X      4        13                                                              3995
            District of Columbia 2010 40   X              2.80877         X       X         X         X        X         X      73       4                                                               2599
            Florida              2010 40   X              X               X       X         X         X        X         X      X        X                                                                  X
            Georgia              2010 40   X              1.6049          X       X         X         X        X         X      647      62                                                             40314
            Hawaii               2010 40   X              1.02934         X       X         X         X        X         X      20       18                                                              1943
            Idaho                2010 40   X              0.414938        X       X         X         X        X         X      19       12                                                              4579
            Illinois             2010 40   X              1.28205         X       X         X         X        X         X      505      74                                                             39390
            Indiana              2010 40   X              0.518962        X       X         X         X        X         X      65       44                                                             12525
            Iowa                 2010 40   X              0.563063        X       X         X         X        X         X      10       6                                                               1776
            Kansas               2010 40   X              0.442227        X       X         X         X        X         X      39       40                                                              8819
            Kentucky             2010 40   X              0.142932        X       X         X         X        X         X      19       14                                                             13293
            Louisiana            2010 40   X              2.28108         X       X         X         X        X         X      391      41                                                             17141
            Maine                2010 40   X              0.357724        X       X         X         X        X         X      22       30                                                              6150
            Maryland             2010 40   X              1.3192          X       X         X         X        X         X      117      17                                                              8869
            Massachusetts        2010 40   X              0.604621        X       X         X         X        X         X      168      56                                                             27786
            Michigan             2010 40   X              0.671831        X       X         X         X        X         X      98       47                                                             14587
            Minnesota            2010 40   X              0.5748          X       X         X         X        X         X      38       17                                                              6611
            Mississippi          2010 40   X              2.9098          X       X         X         X        X         X      491      42                                                             16874
            Missouri             2010 40   X              1.10176         X       X         X         X        X         X      106      33                                                              9621
            Montana              2010 40   X              0.0371195       X       X         X         X        X         X      1        7                                                               2694
            Nebraska             2010 40   X              2.19978         X       X         X         X        X         X      61       13                                                              2773
            Nevada               2010 40   X              1.66683         X       X         X         X        X         X      175      30                                                             10499
...                                                                                                                                                                                                       ...
            Kentucky             2010 41   X              0.223975        X       X         X         X        X         X      23       14                                                             10269
            Louisiana            2010 41   X              2.04776         X       X         X         X        X         X      325      39                                                             15871
            Maine                2010 41   X              0.434855        X       X         X         X        X         X      26       29                                                              5979
            Maryland             2010 41   X              2.09879         X       X         X         X        X         X      99       17                                                              4717
            Massachusetts        2010 41   X              0.887866        X       X         X         X        X         X      216      54                                                             24328
            Michigan             2010 41   X              0.585011        X       X         X         X        X         X      95       53                                                             16239
            Minnesota            2010 41   X              0.541293        X       X         X         X        X         X      35       18                                                              6466
            Mississippi          2010 41   X              2.97075         X       X         X         X        X         X      523      45                                                             17605
            Missouri             2010 41   X              0.930521        X       X         X         X        X         X      90       32                                                              9672
            Montana              2010 41   X              0.180963        X       X         X         X        X         X      5        7                                                               2763
            Nebraska             2010 41   X              2.73532         X       X         X         X        X         X      68       12                                                              2486
            Nevada               2010 41   X              1.63633         X       X         X         X        X         X      187      33                                                             11428
            New Hampshire        2010 41   X              0.0924642       X       X         X         X        X         X      4        22                                                              4326
            New Jersey           2010 41   X              2.47836         X       X         X         X        X         X      189      24                                                              7626
            New Mexico           2010 41   X              1.9635          X       X         X         X        X         X      142      22                                                              7232
            New York             2010 41   X              0.369729        X       X         X         X        X         X      47       89                                                             12712
            North Carolina       2010 41   X              0.53653         X       X         X         X        X         X      141      77                                                             26280
            North Dakota         2010 41   X              0.721961        X       X         X         X        X         X      43       19                                                              5956
            Ohio                 2010 41   X              0.361628        X       X         X         X        X         X      55       44                                                             15209
            Oklahoma             2010 41   X              0.958678        X       X         X         X        X         X      29       17                                                              3025
            Oregon               2010 41   X              0.624076        X       X         X         X        X         X      38       19                                                              6089
            Pennsylvania         2010 41   X              0.910726        X       X         X         X        X         X      157      64                                                             17239
            Rhode Island         2010 41   X              0.201545        X       X         X         X        X         X      12       21                                                              5954
            South Carolina       2010 41   X              0.765523        X       X         X         X        X         X      54       25                                                              7054
            South Dakota         2010 41   X              0.793794        X       X         X         X        X         X      44       18                                                              5543
            Tennessee            2010 41   X              0.499492        X       X         X         X        X         X      59       50                                                             11812
            Texas                2010 41   X              2.09394         X       X         X         X        X         X      1061     97                                                             50670
            Utah                 2010 41   X              0.410939        X       X         X         X        X         X      29       19                                                              7057
            Vermont              2010 41   X              1.35777         X       X         X         X        X         X      40       10                                                              2946
            Virginia             2010 41   X              1.23653         X       X         X         X        X         X      754      83                                                             60977

[100 rows x 1 columns]

In [25]:
fluStates.shape

(26494, 1)

In [22]:
fluStates.shape

(26494, 1)

In [34]:
fluStates.dtypes

PERCENTAGE OF VISITS FOR INFLUENZA-LIKE-ILLNESS REPORTED BY SENTINEL PROVIDERS    object
dtype: object

In [23]:
fluAllSts = fluStates.reset_index()
fluAllSts.head(100)

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,level_10,level_11,level_12,level_13,PERCENTAGE OF VISITS FOR INFLUENZA-LIKE-ILLNESS REPORTED BY SENTINEL PROVIDERS
0,REGION TYPE,REGION,YEAR,WEEK,% WEIGHTED ILI,%UNWEIGHTED ILI,AGE 0-4,AGE 25-49,AGE 25-64,AGE 5-24,AGE 50-64,AGE 65,ILITOTAL,NUM. OF PROVIDERS,TOTAL PATIENTS
1,States,Alabama,2010,40,X,2.13477,X,X,X,X,X,X,249,35,11664
2,States,Alaska,2010,40,X,0.875146,X,X,X,X,X,X,15,7,1714
3,States,Arizona,2010,40,X,0.674721,X,X,X,X,X,X,172,49,25492
4,States,Arkansas,2010,40,X,0.696056,X,X,X,X,X,X,18,15,2586
5,States,California,2010,40,X,1.95412,X,X,X,X,X,X,632,112,32342
6,States,Colorado,2010,40,X,0.660684,X,X,X,X,X,X,134,14,20282
7,States,Connecticut,2010,40,X,0.0783085,X,X,X,X,X,X,3,12,3831
8,States,Delaware,2010,40,X,0.100125,X,X,X,X,X,X,4,13,3995
9,States,District of Columbia,2010,40,X,2.80877,X,X,X,X,X,X,73,4,2599
10,States,Florida,2010,40,X,X,X,X,X,X,X,X,X,X,X
11,States,Georgia,2010,40,X,1.6049,X,X,X,X,X,X,647,62,40314
12,States,Hawaii,2010,40,X,1.02934,X,X,X,X,X,X,20,18,1943
13,States,Idaho,2010,40,X,0.414938,X,X,X,X,X,X,19,12,4579
14,States,Illinois,2010,40,X,1.28205,X,X,X,X,X,X,505,74,39390
15,States,Indiana,2010,40,X,0.518962,X,X,X,X,X,X,65,44,12525
16,States,Iowa,2010,40,X,0.563063,X,X,X,X,X,X,10,6,1776
17,States,Kansas,2010,40,X,0.442227,X,X,X,X,X,X,39,40,8819
18,States,Kentucky,2010,40,X,0.142932,X,X,X,X,X,X,19,14,13293
19,States,Louisiana,2010,40,X,2.28108,X,X,X,X,X,X,391,41,17141
20,States,Maine,2010,40,X,0.357724,X,X,X,X,X,X,22,30,6150
21,States,Maryland,2010,40,X,1.3192,X,X,X,X,X,X,117,17,8869
22,States,Massachusetts,2010,40,X,0.604621,X,X,X,X,X,X,168,56,27786
23,States,Michigan,2010,40,X,0.671831,X,X,X,X,X,X,98,47,14587
24,States,Minnesota,2010,40,X,0.5748,X,X,X,X,X,X,38,17,6611
25,States,Mississippi,2010,40,X,2.9098,X,X,X,X,X,X,491,42,16874
26,States,Missouri,2010,40,X,1.10176,X,X,X,X,X,X,106,33,9621
27,States,Montana,2010,40,X,0.0371195,X,X,X,X,X,X,1,7,2694
28,States,Nebraska,2010,40,X,2.19978,X,X,X,X,X,X,61,13,2773
29,States,Nevada,2010,40,X,1.66683,X,X,X,X,X,X,175,30,10499
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,States,Kentucky,2010,41,X,0.223975,X,X,X,X,X,X,23,14,10269
71,States,Louisiana,2010,41,X,2.04776,X,X,X,X,X,X,325,39,15871
72,States,Maine,2010,41,X,0.434855,X,X,X,X,X,X,26,29,5979
73,States,Maryland,2010,41,X,2.09879,X,X,X,X,X,X,99,17,4717
74,States,Massachusetts,2010,41,X,0.887866,X,X,X,X,X,X,216,54,24328
75,States,Michigan,2010,41,X,0.585011,X,X,X,X,X,X,95,53,16239
76,States,Minnesota,2010,41,X,0.541293,X,X,X,X,X,X,35,18,6466
77,States,Mississippi,2010,41,X,2.97075,X,X,X,X,X,X,523,45,17605
78,States,Missouri,2010,41,X,0.930521,X,X,X,X,X,X,90,32,9672
79,States,Montana,2010,41,X,0.180963,X,X,X,X,X,X,5,7,2763
80,States,Nebraska,2010,41,X,2.73532,X,X,X,X,X,X,68,12,2486
81,States,Nevada,2010,41,X,1.63633,X,X,X,X,X,X,187,33,11428
82,States,New Hampshire,2010,41,X,0.0924642,X,X,X,X,X,X,4,22,4326
83,States,New Jersey,2010,41,X,2.47836,X,X,X,X,X,X,189,24,7626
84,States,New Mexico,2010,41,X,1.9635,X,X,X,X,X,X,142,22,7232
85,States,New York,2010,41,X,0.369729,X,X,X,X,X,X,47,89,12712
86,States,North Carolina,2010,41,X,0.53653,X,X,X,X,X,X,141,77,26280
87,States,North Dakota,2010,41,X,0.721961,X,X,X,X,X,X,43,19,5956
88,States,Ohio,2010,41,X,0.361628,X,X,X,X,X,X,55,44,15209
89,States,Oklahoma,2010,41,X,0.958678,X,X,X,X,X,X,29,17,3025
90,States,Oregon,2010,41,X,0.624076,X,X,X,X,X,X,38,19,6089
91,States,Pennsylvania,2010,41,X,0.910726,X,X,X,X,X,X,157,64,17239
92,States,Rhode Island,2010,41,X,0.201545,X,X,X,X,X,X,12,21,5954
93,States,South Carolina,2010,41,X,0.765523,X,X,X,X,X,X,54,25,7054
94,States,South Dakota,2010,41,X,0.793794,X,X,X,X,X,X,44,18,5543
95,States,Tennessee,2010,41,X,0.499492,X,X,X,X,X,X,59,50,11812
96,States,Texas,2010,41,X,2.09394,X,X,X,X,X,X,1061,97,50670
97,States,Utah,2010,41,X,0.410939,X,X,X,X,X,X,29,19,7057
98,States,Vermont,2010,41,X,1.35777,X,X,X,X,X,X,40,10,2946
99,States,Virginia,2010,41,X,1.23653,X,X,X,X,X,X,754,83,60977

In [36]:
fluAllSts[1:]

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,level_10,level_11,level_12,level_13,PERCENTAGE OF VISITS FOR INFLUENZA-LIKE-ILLNESS REPORTED BY SENTINEL PROVIDERS
1,States,Alabama,2010,40,X,2.13477,X,X,X,X,X,X,249,35,11664
2,States,Alaska,2010,40,X,0.875146,X,X,X,X,X,X,15,7,1714
3,States,Arizona,2010,40,X,0.674721,X,X,X,X,X,X,172,49,25492
4,States,Arkansas,2010,40,X,0.696056,X,X,X,X,X,X,18,15,2586
5,States,California,2010,40,X,1.95412,X,X,X,X,X,X,632,112,32342
6,States,Colorado,2010,40,X,0.660684,X,X,X,X,X,X,134,14,20282
7,States,Connecticut,2010,40,X,0.0783085,X,X,X,X,X,X,3,12,3831
8,States,Delaware,2010,40,X,0.100125,X,X,X,X,X,X,4,13,3995
9,States,District of Columbia,2010,40,X,2.80877,X,X,X,X,X,X,73,4,2599
10,States,Florida,2010,40,X,X,X,X,X,X,X,X,X,X,X
11,States,Georgia,2010,40,X,1.6049,X,X,X,X,X,X,647,62,40314
12,States,Hawaii,2010,40,X,1.02934,X,X,X,X,X,X,20,18,1943
13,States,Idaho,2010,40,X,0.414938,X,X,X,X,X,X,19,12,4579
14,States,Illinois,2010,40,X,1.28205,X,X,X,X,X,X,505,74,39390
15,States,Indiana,2010,40,X,0.518962,X,X,X,X,X,X,65,44,12525
16,States,Iowa,2010,40,X,0.563063,X,X,X,X,X,X,10,6,1776
17,States,Kansas,2010,40,X,0.442227,X,X,X,X,X,X,39,40,8819
18,States,Kentucky,2010,40,X,0.142932,X,X,X,X,X,X,19,14,13293
19,States,Louisiana,2010,40,X,2.28108,X,X,X,X,X,X,391,41,17141
20,States,Maine,2010,40,X,0.357724,X,X,X,X,X,X,22,30,6150
21,States,Maryland,2010,40,X,1.3192,X,X,X,X,X,X,117,17,8869
22,States,Massachusetts,2010,40,X,0.604621,X,X,X,X,X,X,168,56,27786
23,States,Michigan,2010,40,X,0.671831,X,X,X,X,X,X,98,47,14587
24,States,Minnesota,2010,40,X,0.5748,X,X,X,X,X,X,38,17,6611
25,States,Mississippi,2010,40,X,2.9098,X,X,X,X,X,X,491,42,16874
26,States,Missouri,2010,40,X,1.10176,X,X,X,X,X,X,106,33,9621
27,States,Montana,2010,40,X,0.0371195,X,X,X,X,X,X,1,7,2694
28,States,Nebraska,2010,40,X,2.19978,X,X,X,X,X,X,61,13,2773
29,States,Nevada,2010,40,X,1.66683,X,X,X,X,X,X,175,30,10499
30,States,New Hampshire,2010,40,X,0.0759301,X,X,X,X,X,X,3,21,3951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26464,States,Missouri,2020,12,X,6.32353,X,X,X,X,X,X,43,8,680
26465,States,Montana,2020,12,X,4.6387,X,X,X,X,X,X,355,34,7653
26466,States,Nebraska,2020,12,X,6.41347,X,X,X,X,X,X,537,59,8373
26467,States,Nevada,2020,12,X,2.82371,X,X,X,X,X,X,181,19,6410
26468,States,New Hampshire,2020,12,X,1.40735,X,X,X,X,X,X,18,9,1279
26469,States,New Jersey,2020,12,X,13.4475,X,X,X,X,X,X,3103,29,23075
26470,States,New Mexico,2020,12,X,5.81922,X,X,X,X,X,X,1144,44,19659
26471,States,New York,2020,12,X,8.01075,X,X,X,X,X,X,3278,122,40920
26472,States,North Carolina,2020,12,X,5.18066,X,X,X,X,X,X,4270,140,82422
26473,States,North Dakota,2020,12,X,7.82811,X,X,X,X,X,X,235,11,3002
26474,States,Ohio,2020,12,X,3.269,X,X,X,X,X,X,249,36,7617
26475,States,Oklahoma,2020,12,X,8.41655,X,X,X,X,X,X,590,25,7010
26476,States,Oregon,2020,12,X,6.79819,X,X,X,X,X,X,2226,92,32744
26477,States,Pennsylvania,2020,12,X,6.61517,X,X,X,X,X,X,3314,117,50097
26478,States,Rhode Island,2020,12,X,1.62602,X,X,X,X,X,X,30,14,1845
26479,States,South Carolina,2020,12,X,9.82817,X,X,X,X,X,X,898,23,9137
26480,States,South Dakota,2020,12,X,2.91717,X,X,X,X,X,X,218,31,7473
26481,States,Tennessee,2020,12,X,7.61454,X,X,X,X,X,X,2591,67,34027
26482,States,Texas,2020,12,X,8.12447,X,X,X,X,X,X,1812,91,22303
26483,States,Utah,2020,12,X,6.33739,X,X,X,X,X,X,979,51,15448
26484,States,Vermont,2020,12,X,4.81125,X,X,X,X,X,X,130,15,2702
26485,States,Virginia,2020,12,X,7.37984,X,X,X,X,X,X,5968,163,80869
26486,States,Washington,2020,12,X,6.11824,X,X,X,X,X,X,920,50,15037
26487,States,West Virginia,2020,12,X,5.33761,X,X,X,X,X,X,366,31,6857
26488,States,Wisconsin,2020,12,X,6.29862,X,X,X,X,X,X,1255,40,19925
26489,States,Wyoming,2020,12,X,4.03155,X,X,X,X,X,X,46,9,1141
26490,States,Commonwealth of the Northern Mariana Islands,2020,12,X,X,X,X,X,X,X,X,X,X,X
26491,States,Puerto Rico,2020,12,X,19.708,X,X,X,X,X,X,135,5,685
26492,States,Virgin Islands,2020,12,X,1.89873,X,X,X,X,X,X,6,2,316
26493,States,New York City,2020,12,X,12.2196,X,X,X,X,X,X,9854,58,80641

In [54]:
fluAllSts.iloc[0]

level_0                                                                                 REGION TYPE
level_1                                                                                      REGION
level_2                                                                                        YEAR
level_3                                                                                        WEEK
level_4                                                                              % WEIGHTED ILI
level_5                                                                             %UNWEIGHTED ILI
level_6                                                                                     AGE 0-4
level_7                                                                                   AGE 25-49
level_8                                                                                   AGE 25-64
level_9                                                                                    AGE 5-24
level_10                                                                                  AGE 50-64
level_11                                                                                     AGE 65
level_12                                                                                   ILITOTAL
level_13                                                                          NUM. OF PROVIDERS
PERCENTAGE OF VISITS FOR INFLUENZA-LIKE-ILLNESS REPORTED BY SENTINEL PROVIDERS       TOTAL PATIENTS
Name: 0, dtype: object

In [24]:
fluFinal = fluAllSts[1:].copy()
fluFinal.head(10)

,level_0,level_1,level_2,level_3,level_4,level_5,level_6,level_7,level_8,level_9,level_10,level_11,level_12,level_13,PERCENTAGE OF VISITS FOR INFLUENZA-LIKE-ILLNESS REPORTED BY SENTINEL PROVIDERS
1,States,Alabama,2010,40,X,2.13477,X,X,X,X,X,X,249,35,11664
2,States,Alaska,2010,40,X,0.875146,X,X,X,X,X,X,15,7,1714
3,States,Arizona,2010,40,X,0.674721,X,X,X,X,X,X,172,49,25492
4,States,Arkansas,2010,40,X,0.696056,X,X,X,X,X,X,18,15,2586
5,States,California,2010,40,X,1.95412,X,X,X,X,X,X,632,112,32342
6,States,Colorado,2010,40,X,0.660684,X,X,X,X,X,X,134,14,20282
7,States,Connecticut,2010,40,X,0.0783085,X,X,X,X,X,X,3,12,3831
8,States,Delaware,2010,40,X,0.100125,X,X,X,X,X,X,4,13,3995
9,States,District of Columbia,2010,40,X,2.80877,X,X,X,X,X,X,73,4,2599
10,States,Florida,2010,40,X,X,X,X,X,X,X,X,X,X,X

In [25]:
fluFinal.columns = fluAllSts.iloc[0]

In [26]:
fluFinal.head(10)

,REGION TYPE,REGION,YEAR,WEEK,% WEIGHTED ILI,%UNWEIGHTED ILI,AGE 0-4,AGE 25-49,AGE 25-64,AGE 5-24,AGE 50-64,AGE 65,ILITOTAL,NUM. OF PROVIDERS,TOTAL PATIENTS
1,States,Alabama,2010,40,X,2.13477,X,X,X,X,X,X,249,35,11664
2,States,Alaska,2010,40,X,0.875146,X,X,X,X,X,X,15,7,1714
3,States,Arizona,2010,40,X,0.674721,X,X,X,X,X,X,172,49,25492
4,States,Arkansas,2010,40,X,0.696056,X,X,X,X,X,X,18,15,2586
5,States,California,2010,40,X,1.95412,X,X,X,X,X,X,632,112,32342
6,States,Colorado,2010,40,X,0.660684,X,X,X,X,X,X,134,14,20282
7,States,Connecticut,2010,40,X,0.0783085,X,X,X,X,X,X,3,12,3831
8,States,Delaware,2010,40,X,0.100125,X,X,X,X,X,X,4,13,3995
9,States,District of Columbia,2010,40,X,2.80877,X,X,X,X,X,X,73,4,2599
10,States,Florida,2010,40,X,X,X,X,X,X,X,X,X,X,X

In [29]:
fluFinal['YEAR'] = fluFinal['YEAR'].fillna(1753)

In [32]:
fluFinal['YEAR'] = fluFinal['YEAR'].astype('int64')

In [34]:
fluFinal[fluFinal['YEAR'] >= 2015].head(50)

,REGION TYPE,REGION,YEAR,WEEK,% WEIGHTED ILI,%UNWEIGHTED ILI,AGE 0-4,AGE 25-49,AGE 25-64,AGE 5-24,AGE 50-64,AGE 65,ILITOTAL,NUM. OF PROVIDERS,TOTAL PATIENTS
11781,States,Alabama,2015,1,X,5.42916,X,X,X,X,X,X,525,23,9670
11782,States,Alaska,2015,1,X,0.975177,X,X,X,X,X,X,11,8,1128
11783,States,Arizona,2015,1,X,2.65774,X,X,X,X,X,X,639,60,24043
11784,States,Arkansas,2015,1,X,5.29005,X,X,X,X,X,X,321,19,6068
11785,States,California,2015,1,X,3.99683,X,X,X,X,X,X,1865,157,46662
11786,States,Colorado,2015,1,X,3.56194,X,X,X,X,X,X,134,6,3762
11787,States,Connecticut,2015,1,X,2.2769,X,X,X,X,X,X,62,16,2723
11788,States,Delaware,2015,1,X,1.35514,X,X,X,X,X,X,29,9,2140
11789,States,District of Columbia,2015,1,X,12.6485,X,X,X,X,X,X,181,2,1431
11790,States,Florida,2015,1,X,X,X,X,X,X,X,X,X,X,X
11791,States,Georgia,2015,1,X,3.11618,X,X,X,X,X,X,762,34,24453
11792,States,Hawaii,2015,1,X,11.99,X,X,X,X,X,X,335,19,2794
11793,States,Idaho,2015,1,X,5.63751,X,X,X,X,X,X,214,10,3796
11794,States,Illinois,2015,1,X,3.07323,X,X,X,X,X,X,1397,93,45457
11795,States,Indiana,2015,1,X,3.40893,X,X,X,X,X,X,239,36,7011
11796,States,Iowa,2015,1,X,4.01544,X,X,X,X,X,X,104,12,2590
11797,States,Kansas,2015,1,X,6.33073,X,X,X,X,X,X,397,31,6271
11798,States,Kentucky,2015,1,X,2.36296,X,X,X,X,X,X,494,20,20906
11799,States,Louisiana,2015,1,X,4.77709,X,X,X,X,X,X,2127,75,44525
11800,States,Maine,2015,1,X,2.23803,X,X,X,X,X,X,129,30,5764
11801,States,Maryland,2015,1,X,2.78897,X,X,X,X,X,X,346,24,12406
11802,States,Massachusetts,2015,1,X,1.76238,X,X,X,X,X,X,468,47,26555
11803,States,Michigan,2015,1,X,2.35103,X,X,X,X,X,X,391,52,16631
11804,States,Minnesota,2015,1,X,3.64327,X,X,X,X,X,X,163,15,4474
11805,States,Mississippi,2015,1,X,5.57493,X,X,X,X,X,X,1103,53,19785
11806,States,Missouri,2015,1,X,4.37008,X,X,X,X,X,X,333,23,7620
11807,States,Montana,2015,1,X,1.40569,X,X,X,X,X,X,43,11,3059
11808,States,Nebraska,2015,1,X,2.82328,X,X,X,X,X,X,81,15,2869
11809,States,Nevada,2015,1,X,3.93077,X,X,X,X,X,X,486,27,12364
11810,States,New Hampshire,2015,1,X,1.11036,X,X,X,X,X,X,49,26,4413
11811,States,New Jersey,2015,1,X,3.62311,X,X,X,X,X,X,343,26,9467
11812,States,New Mexico,2015,1,X,3.97067,X,X,X,X,X,X,509,26,12819
11813,States,New York,2015,1,X,4.20694,X,X,X,X,X,X,370,84,8795
11814,States,North Carolina,2015,1,X,3.79011,X,X,X,X,X,X,567,52,14960
11815,States,North Dakota,2015,1,X,3.37739,X,X,X,X,X,X,69,10,2043
11816,States,Ohio,2015,1,X,3.43176,X,X,X,X,X,X,480,57,13987
11817,States,Oklahoma,2015,1,X,5.88416,X,X,X,X,X,X,192,19,3263
11818,States,Oregon,2015,1,X,1.52801,X,X,X,X,X,X,63,17,4123
11819,States,Pennsylvania,2015,1,X,4.48301,X,X,X,X,X,X,558,44,12447
11820,States,Rhode Island,2015,1,X,1.94729,X,X,X,X,X,X,99,20,5084
11821,States,South Carolina,2015,1,X,3.06247,X,X,X,X,X,X,150,12,4898
11822,States,South Dakota,2015,1,X,2.52855,X,X,X,X,X,X,155,25,6130
11823,States,Tennessee,2015,1,X,5.80371,X,X,X,X,X,X,560,49,9649
11824,States,Texas,2015,1,X,9.06724,X,X,X,X,X,X,1776,84,19587
11825,States,Utah,2015,1,X,4.24488,X,X,X,X,X,X,900,43,21202
11826,States,Vermont,2015,1,X,3.10345,X,X,X,X,X,X,108,12,3480
11827,States,Virginia,2015,1,X,6.49073,X,X,X,X,X,X,5679,124,87494
11828,States,Washington,2015,1,X,3.64139,X,X,X,X,X,X,158,41,4339
11829,States,West Virginia,2015,1,X,6.14404,X,X,X,X,X,X,964,44,15690
11830,States,Wisconsin,2015,1,X,3.71117,X,X,X,X,X,X,221,29,5955

In [46]:
noAgeCols =[col for col in fluFinal.columns if not col.startswith('AGE')]
noAgeCols

['REGION TYPE',
 'REGION',
 'YEAR',
 'WEEK',
 '% WEIGHTED ILI',
 '%UNWEIGHTED ILI',
 'ILITOTAL',
 'NUM. OF PROVIDERS',
 'TOTAL PATIENTS']

In [47]:
noAgeCols.remove('% WEIGHTED ILI')
noAgeCols

['REGION TYPE',
 'REGION',
 'YEAR',
 'WEEK',
 '%UNWEIGHTED ILI',
 'ILITOTAL',
 'NUM. OF PROVIDERS',
 'TOTAL PATIENTS']

In [ ]:
fluFinal

In [7]:
#https://www.kff.org/medicaid/issue-brief/status-of-state-medicaid-expansion-decisions-interactive-map/
medicaidExp = pd.read_csv('medicaidexpansionmap.csv')
medicaidExp

,State,Expansion Status,Description
0,Alabama,Not Adopted,NaN
1,Alaska,Adopted and Implemented,Implemented expansion on 9/1/2015\n
2,Arizona,Adopted and Implemented,Implemented expansion on 1/1/2014\n
3,Arkansas,Adopted and Implemented,Implemented expansion on 1/1/2014 \n
4,California,Adopted and Implemented,Implemented expansion on 1/1/2014\n
5,Colorado,Adopted and Implemented,Implemented expansion on 1/1/2014\n
6,Connecticut,Adopted and Implemented,Implemented expansion on 1/1/2014\n
7,Delaware,Adopted and Implemented,Implemented expansion on 1/1/2014\n
8,District of Columbia,Adopted and Implemented,Implemented expansion on 1/1/2014\n
9,Florida,Not Adopted,NaN
10,Georgia,Not Adopted,NaN
11,Hawaii,Adopted and Implemented,Implemented expansion on 1/1/2014\n
12,Idaho,Adopted and Implemented,Expansion coverage implemented 1/1/2020 (enrol...
13,Illinois,Adopted and Implemented,Implemented expansion on 1/1/2014\n
14,Indiana,Adopted and Implemented,Implemented expansion on 2/1/2015\n
15,Iowa,Adopted and Implemented,Implemented expansion on 1/1/2014\n
16,Kansas,Not Adopted,NaN
17,Kentucky,Adopted and Implemented,Implemented expansion on 1/1/2014\n
18,Louisiana,Adopted and Implemented,Implemented expansion on 7/1/2016\n
19,Maine,Adopted and Implemented,Implemented expansion on 1/10/2019 with covera...
20,Maryland,Adopted and Implemented,Implemented expansion on 1/1/2014\n
21,Massachusetts,Adopted and Implemented,Implemented expansion on 1/1/2014\n
22,Michigan,Adopted and Implemented,Implemented expansion on 4/1/2014\n
23,Minnesota,Adopted and Implemented,Implemented expansion on 1/1/2014\n
24,Mississippi,Not Adopted,NaN
25,Missouri,Not Adopted,NaN
26,Montana,Adopted and Implemented,Implemented expansion on 1/1/2016\n
27,Nebraska,Adopted but Not Implemented,NaN
28,Nevada,Adopted and Implemented,Implemented expansion on 1/1/2014\n
29,New Hampshire,Adopted and Implemented,Implemented expansion on 8/15/2014
30,New Jersey,Adopted and Implemented,Implemented expansion on 1/1/2014\n
31,New Mexico,Adopted and Implemented,Implemented expansion on 1/1/2014\n
32,New York,Adopted and Implemented,Implemented expansion on 1/1/2014\n
33,North Carolina,Not Adopted,NaN
34,North Dakota,Adopted and Implemented,Implemented expansion on 1/1/2014\n
35,Ohio,Adopted and Implemented,Implemented expansion on 1/1/2014\n
36,Oklahoma,Not Adopted,NaN
37,Oregon,Adopted and Implemented,Implemented expansion on 1/1/2014\n
38,Pennsylvania,Adopted and Implemented,Implemented expansion on 1/1/2015\n
39,Rhode Island,Adopted and Implemented,Implemented expansion on 1/1/2014\n
40,South Carolina,Not Adopted,NaN
41,South Dakota,Not Adopted,NaN
42,Tennessee,Not Adopted,NaN
43,Texas,Not Adopted,NaN
44,Utah,Adopted and Implemented,Implemented expansion on 1/1/2020
45,Vermont,Adopted and Implemented,Implemented expansion on 1/1/2014\n
46,Virginia,Adopted and Implemented,Expansion coverage implemented 1/1/2019 (enrol...
47,Washington,Adopted and Implemented,Implemented expansion on 1/1/2014\n
48,West Virginia,Adopted and Implemented,Implemented expansion on 1/1/2014\n
49,Wisconsin,Not Adopted,NaN
50,Wyoming,Not Adopted,NaN

In [8]:
medicaidExp.fillna('NA', inplace=True)

In [9]:
dfimpdt = medicaidExp['Description'].str.extract('(\d+/\d+/\d+)')

In [85]:
dfimpdt[0]

0           NaN
1      9/1/2015
2      1/1/2014
3      1/1/2014
4      1/1/2014
5      1/1/2014
6      1/1/2014
7      1/1/2014
8      1/1/2014
9           NaN
10          NaN
11     1/1/2014
12     1/1/2020
13     1/1/2014
14     2/1/2015
15     1/1/2014
16          NaN
17     1/1/2014
18     7/1/2016
19    1/10/2019
20     1/1/2014
21     1/1/2014
22     4/1/2014
23     1/1/2014
24          NaN
25          NaN
26     1/1/2016
27          NaN
28     1/1/2014
29    8/15/2014
30     1/1/2014
31     1/1/2014
32     1/1/2014
33          NaN
34     1/1/2014
35     1/1/2014
36          NaN
37     1/1/2014
38     1/1/2015
39     1/1/2014
40          NaN
41          NaN
42          NaN
43          NaN
44     1/1/2020
45     1/1/2014
46     1/1/2019
47     1/1/2014
48     1/1/2014
49          NaN
50          NaN
Name: 0, dtype: object

In [10]:
medicaidExp['Implemented_Dt'] = pd.to_datetime(dfimpdt[0])

In [11]:
medicaidExp

,State,Expansion Status,Description,Implemented_Dt
0,Alabama,Not Adopted,NA,NaT
1,Alaska,Adopted and Implemented,Implemented expansion on 9/1/2015\n,2015-09-01
2,Arizona,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
3,Arkansas,Adopted and Implemented,Implemented expansion on 1/1/2014 \n,2014-01-01
4,California,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
5,Colorado,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
6,Connecticut,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
7,Delaware,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
8,District of Columbia,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
9,Florida,Not Adopted,NA,NaT
10,Georgia,Not Adopted,NA,NaT
11,Hawaii,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
12,Idaho,Adopted and Implemented,Expansion coverage implemented 1/1/2020 (enrol...,2020-01-01
13,Illinois,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
14,Indiana,Adopted and Implemented,Implemented expansion on 2/1/2015\n,2015-02-01
15,Iowa,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
16,Kansas,Not Adopted,NA,NaT
17,Kentucky,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
18,Louisiana,Adopted and Implemented,Implemented expansion on 7/1/2016\n,2016-07-01
19,Maine,Adopted and Implemented,Implemented expansion on 1/10/2019 with covera...,2019-01-10
20,Maryland,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
21,Massachusetts,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
22,Michigan,Adopted and Implemented,Implemented expansion on 4/1/2014\n,2014-04-01
23,Minnesota,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
24,Mississippi,Not Adopted,NA,NaT
25,Missouri,Not Adopted,NA,NaT
26,Montana,Adopted and Implemented,Implemented expansion on 1/1/2016\n,2016-01-01
27,Nebraska,Adopted but Not Implemented,NA,NaT
28,Nevada,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
29,New Hampshire,Adopted and Implemented,Implemented expansion on 8/15/2014,2014-08-15
30,New Jersey,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
31,New Mexico,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
32,New York,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
33,North Carolina,Not Adopted,NA,NaT
34,North Dakota,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
35,Ohio,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
36,Oklahoma,Not Adopted,NA,NaT
37,Oregon,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
38,Pennsylvania,Adopted and Implemented,Implemented expansion on 1/1/2015\n,2015-01-01
39,Rhode Island,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
40,South Carolina,Not Adopted,NA,NaT
41,South Dakota,Not Adopted,NA,NaT
42,Tennessee,Not Adopted,NA,NaT
43,Texas,Not Adopted,NA,NaT
44,Utah,Adopted and Implemented,Implemented expansion on 1/1/2020,2020-01-01
45,Vermont,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
46,Virginia,Adopted and Implemented,Expansion coverage implemented 1/1/2019 (enrol...,2019-01-01
47,Washington,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
48,West Virginia,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
49,Wisconsin,Not Adopted,NA,NaT
50,Wyoming,Not Adopted,NA,NaT

In [94]:
over200 = df[(df['Confirmed'] >= 200) & (df['Country_Region'] == 'US')]
over200['DeathToConf'] = over200['Deaths'] / df['Confirmed']
over200

/Users/dineshmurali/miniconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,DeathToConf
18,6001.0,Alameda,California,US,2020-04-01 21:58:49,37.646294,-121.892927,313,7,0,0,"Alameda, California, US",0.022364
20,36001.0,Albany,New York,US,2020-04-01 21:58:49,42.600603,-73.977239,240,1,0,0,"Albany, New York, US",0.004167
31,42003.0,Allegheny,Pennsylvania,US,2020-04-01 21:58:49,40.468099,-79.981677,356,2,0,0,"Allegheny, Pennsylvania, US",0.005618
59,8005.0,Arapahoe,Colorado,US,2020-04-01 21:58:49,39.649775,-104.335362,333,6,0,0,"Arapahoe, Colorado, US",0.018018
90,24005.0,Baltimore,Maryland,US,2020-04-01 21:58:49,39.457847,-76.629120,289,1,0,0,"Baltimore, Maryland, US",0.003460
91,24510.0,Baltimore City,Maryland,US,2020-04-01 21:58:49,39.302119,-76.611510,221,2,0,0,"Baltimore City, Maryland, US",0.009050
97,25001.0,Barnstable,Massachusetts,US,2020-04-01 21:58:49,41.729806,-70.288543,255,3,0,0,"Barnstable, Massachusetts, US",0.011765
136,34003.0,Bergen,New Jersey,US,2020-04-01 21:58:49,40.960109,-74.071643,3494,75,0,0,"Bergen, New Jersey, US",0.021465
145,48029.0,Bexar,Texas,US,2020-04-01 21:58:49,29.449287,-98.520197,207,9,0,0,"Bexar, Texas, US",0.043478
152,16013.0,Blaine,Idaho,US,2020-04-01 21:58:49,43.408581,-113.975266,228,2,0,0,"Blaine, Idaho, US",0.008772
191,25005.0,Bristol,Massachusetts,US,2020-04-01 21:58:49,41.792284,-71.108722,366,3,0,0,"Bristol, Massachusetts, US",0.008197
199,12011.0,Broward,Florida,US,2020-04-01 21:58:49,26.151847,-80.487256,1232,12,0,0,"Broward, Florida, US",0.009740
213,42017.0,Bucks,Pennsylvania,US,2020-04-01 21:58:49,40.336821,-75.108366,319,6,0,0,"Bucks, Pennsylvania, US",0.018809
226,34005.0,Burlington,New Jersey,US,2020-04-01 21:58:49,39.876811,-74.669278,255,5,0,0,"Burlington, New Jersey, US",0.019608
241,22017.0,Caddo,Louisiana,US,2020-04-01 21:58:49,32.579916,-93.883757,298,7,0,0,"Caddo, Louisiana, US",0.023490
264,34007.0,Camden,New Jersey,US,2020-04-01 21:58:49,39.803438,-74.963888,289,3,0,0,"Camden, New Jersey, US",0.010381
386,32003.0,Clark,Nevada,US,2020-04-01 21:58:49,36.214589,-115.013024,961,28,0,0,"Clark, Nevada, US",0.029136
427,13067.0,Cobb,Georgia,US,2020-04-01 21:58:49,33.942432,-84.576126,293,15,0,0,"Cobb, Georgia, US",0.051195
457,6013.0,Contra Costa,California,US,2020-04-01 21:58:49,37.919235,-121.928953,249,3,0,0,"Contra Costa, California, US",0.012048
461,17031.0,Cook,Illinois,US,2020-04-01 21:58:49,41.841448,-87.816588,5152,95,0,0,"Cook, Illinois, US",0.018439
510,39035.0,Cuyahoga,Ohio,US,2020-04-01 21:58:49,41.424119,-81.659183,589,9,0,0,"Cuyahoga, Ohio, US",0.015280
515,48113.0,Dallas,Texas,US,2020-04-01 21:58:49,32.766706,-96.777961,731,15,0,0,"Dallas, Texas, US",0.020520
516,55025.0,Dane,Wisconsin,US,2020-04-01 21:58:49,43.066016,-89.417338,215,2,0,0,"Dane, Wisconsin, US",0.009302
523,47037.0,Davidson,Tennessee,US,2020-04-01 21:58:49,36.170074,-86.786461,673,4,0,0,"Davidson, Tennessee, US",0.005944
533,13089.0,DeKalb,Georgia,US,2020-04-01 21:58:49,33.769440,-84.223960,365,4,0,0,"DeKalb, Georgia, US",0.010959
552,42045.0,Delaware,Pennsylvania,US,2020-04-01 21:58:49,39.916802,-75.402437,390,7,0,0,"Delaware, Pennsylvania, US",0.017949
555,48121.0,Denton,Texas,US,2020-04-01 21:58:49,33.205219,-97.116912,206,4,0,0,"Denton, Texas, US",0.019417
556,8031.0,Denver,Colorado,US,2020-04-01 21:58:49,39.760183,-104.872569,539,7,0,0,"Denver, Colorado, US",0.012987
565,11001.0,District of Columbia,District of Columbia,US,2020-04-01 21:58:49,38.904178,-77.016560,586,9,0,0,"District of Columbia,District of Columbia,US",0.015358
578,13095.0,Dougherty,Georgia,US,2020-04-01 21:58:49,31.533285,-84.217224,480,27,0,0,"Dougherty, Georgia, US",0.056250
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1722,49035.0,Salt Lake,Utah,US,2020-04-01 21:58:49,40.666165,-111.921601,396,2,0,0,"Salt Lake, Utah, US",0.005051
1728,6073.0,San Diego,California,US,2020-04-01 21:58:49,33.034846,-116.736533,733,9,0,0,"San Diego, California, US",0.012278
1729,6075.0,San Francisco,California,US,2020-04-01 21:58:49,37.752151,-122.438567,434,7,0,0,"San Francisco, California, US",0.016129
1736,6081.0,San Mateo,California,US,2020-04-01 21:58:49,37.422881,-122.327555,388,10,0,0,"San Mateo, California, US",0.025773
1745,6085.0,Santa Clara,California,US,2020-04-01 21:58:49,37.231049,-121.697046,956,32,0,0,"Santa Clara, California, US",0.033473
1794,47157.0,Shelby,Tennessee,US,2020-04-01 21:58:49,35.186478,-89.896924,496,1,0,0,"Shelby, Tennessee, US",0.002016
1813,53061.0,Snohomish,Washington,US,2020-04-01 21:58:49,48.046160,-121.717070,1304,40,0,0,"Snohomish, Washington, US",0.030675
1819,34035.0,Somerset,New Jersey,US,2020-04-01 21:58:49,40.564657,-74.616830,472,15,0,0,"Somerset, New Jersey, US",0.031780
1846,29189.0,St. Louis,Missouri,US,2020-04-01 21:58:49,38.637700,-90.445837,605,3,0,0,"St. Louis, Missouri, US",0.004959
1852,22103.0,St. Tammany,Louisiana,US,2020-04-01 21:58:49,30.409428,-89.956427,270,6,0,0,"St. Tammany, Louisiana, US",0.022222
1879,25025.0,Suffolk,Massachusetts,US,2020-04-01 21:58:49,42.327951,-71.078504,1624,13,0,0,"Suffolk, Massachusetts, US",0.008005
1880,36103.0,Suffolk,New York,US,2020-04-01 21:58:49,40.883201,-72.801217,7605,53,0,0,"Suffolk, New York, US",0.006969
1890,47165.0,Sumner,Tennessee,US,2020-04-01 21:58:49,36.468241,-86.459172,201,4,0,0,"Sumner, Tennessee, US",0.019900
1916,48439.0,Tarrant,Texas,US,2020-04-01 21:58:49,32.771438,-97.291016,288,3,0,0,"Tarrant, Texas, US",0.010417
1954,48453.0,Travis,Texas,US,2020-04-01 21:58:49,30.334320,-97.785356,244,2,0,0,"Travis, Texas, US",0.008197
1972,36111.0,Ulster,New York,US,2020-04-01 21:58:49,41.890279,-74.262521,222,3,0,0,"Ulster, New York, US",0.013514
1982,NaN,Unassigned,Georgia,US,2020-04-01 21:58:49,0.000000,0.000000,516,2,0,0,"Unassigned, Georgia, US",0.003876
1990,NaN,Unassigned,Massachusetts,US,2020-04-01 21:58:49,0.000000,0.000000,251,9,0,0,"Unassigned, Massachusetts, US",0.035857
1997,NaN,Unassigned,New Jersey,US,2020-04-01 21:58:49,0.000000,0.000000,4512,0,0,0,"Unassigned, New Jersey, US",0.000000
2001,NaN,Unassigned,Tennessee,US,2020-04-01 21:58:49,0.000000,0.000000,442,11,0,0,"Unassigned, Tennessee, US",0.024887
2004,NaN,Unassigned,Washington,US,2020-04-01 21:58:49,0.000000,0.000000,303,0,0,0,"Unassigned, Washington, US",0.000000
2012,34039.0,Union,New Jersey,US,2020-04-01 21:58:49,40.658354,-74.306801,1661,29,0,0,"Union, New Jersey, US",0.017459
2047,37183.0,Wake,North Carolina,US,2020-04-01 21:58:49,35.788793,-78.652492,213,0,0,0,"Wake, North Carolina, US",0.000000
2109,26161.0,Washtenaw,Michigan,US,2020-04-01 21:58:49,42.253105,-83.838532,401,8,0,0,"Washtenaw, Michigan, US",0.019950
2116,26163.0,Wayne,Michigan,US,2020-04-01 21:58:49,42.278056,-83.378611,4470,146,0,0,"Wayne,Michigan,US",0.032662
2132,8123.0,Weld,Colorado,US,2020-04-01 21:58:49,40.554994,-104.392962,255,12,0,0,"Weld, Colorado, US",0.047059
2136,36119.0,Westchester,New York,US,2020-04-01 21:58:49,41.162784,-73.757417,10683,25,0,0,"Westchester, New York, US",0.002340
2161,17197.0,Will,Illinois,US,2020-04-01 21:58:49,41.446193,-87.978627,322,9,0,0,"Will, Illinois, US",0.027950
2195,25027.0,Worcester,Massachusetts,US,2020-04-01 21:58:49,42.350270,-71.904934,563,9,0,0,"Worcester, Massachusetts, US",0.015986
2281,NaN,NaN,Puerto Rico,US,2020-04-01 21:58:49,18.220800,-66.590100,286,11,0,0,"Puerto Rico, US",0.038462

In [ ]:
#hospital beds: https://docs.google.com/spreadsheets/d/1xAyBFTrlxSsTKQS7IDyr_Ah4JLBYj6_HX6ijKdm4fAY/edit#gid=0
#hospitals https://data.medicare.gov/widgets/xubh-q36u , already downloaded

In [12]:
medicaidExp.rename(columns={'State':'Province_State'},inplace=True)

In [13]:
medicaidExp

,Province_State,Expansion Status,Description,Implemented_Dt
0,Alabama,Not Adopted,NA,NaT
1,Alaska,Adopted and Implemented,Implemented expansion on 9/1/2015\n,2015-09-01
2,Arizona,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
3,Arkansas,Adopted and Implemented,Implemented expansion on 1/1/2014 \n,2014-01-01
4,California,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
5,Colorado,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
6,Connecticut,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
7,Delaware,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
8,District of Columbia,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
9,Florida,Not Adopted,NA,NaT
10,Georgia,Not Adopted,NA,NaT
11,Hawaii,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
12,Idaho,Adopted and Implemented,Expansion coverage implemented 1/1/2020 (enrol...,2020-01-01
13,Illinois,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
14,Indiana,Adopted and Implemented,Implemented expansion on 2/1/2015\n,2015-02-01
15,Iowa,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
16,Kansas,Not Adopted,NA,NaT
17,Kentucky,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
18,Louisiana,Adopted and Implemented,Implemented expansion on 7/1/2016\n,2016-07-01
19,Maine,Adopted and Implemented,Implemented expansion on 1/10/2019 with covera...,2019-01-10
20,Maryland,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
21,Massachusetts,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
22,Michigan,Adopted and Implemented,Implemented expansion on 4/1/2014\n,2014-04-01
23,Minnesota,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
24,Mississippi,Not Adopted,NA,NaT
25,Missouri,Not Adopted,NA,NaT
26,Montana,Adopted and Implemented,Implemented expansion on 1/1/2016\n,2016-01-01
27,Nebraska,Adopted but Not Implemented,NA,NaT
28,Nevada,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
29,New Hampshire,Adopted and Implemented,Implemented expansion on 8/15/2014,2014-08-15
30,New Jersey,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
31,New Mexico,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
32,New York,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
33,North Carolina,Not Adopted,NA,NaT
34,North Dakota,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
35,Ohio,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
36,Oklahoma,Not Adopted,NA,NaT
37,Oregon,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
38,Pennsylvania,Adopted and Implemented,Implemented expansion on 1/1/2015\n,2015-01-01
39,Rhode Island,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
40,South Carolina,Not Adopted,NA,NaT
41,South Dakota,Not Adopted,NA,NaT
42,Tennessee,Not Adopted,NA,NaT
43,Texas,Not Adopted,NA,NaT
44,Utah,Adopted and Implemented,Implemented expansion on 1/1/2020,2020-01-01
45,Vermont,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
46,Virginia,Adopted and Implemented,Expansion coverage implemented 1/1/2019 (enrol...,2019-01-01
47,Washington,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
48,West Virginia,Adopted and Implemented,Implemented expansion on 1/1/2014\n,2014-01-01
49,Wisconsin,Not Adopted,NA,NaT
50,Wyoming,Not Adopted,NA,NaT

In [117]:
usa.dtypes

FIPS              float64
Admin2             object
Province_State     object
Country_Region     object
Last_Update        object
Lat               float64
Long_             float64
Confirmed           int64
Deaths              int64
Recovered           int64
Active              int64
Combined_Key       object
dtype: object

In [118]:
medicaidExp.dtypes

Province_State              object
Expansion Status            object
Description                 object
Implemented_Dt      datetime64[ns]
dtype: object

In [14]:
usaMedicaid = pd.merge(usa,medicaidExp, on='Province_State', how='left').drop(columns=['Expansion Status','Description'])
usaMedicaid

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Implemented_Dt
0,45001.0,Abbeville,South Carolina,US,2020-04-03 22:46:37,34.223334,-82.461707,6,0,0,0,"Abbeville, South Carolina, US",NaT
1,22001.0,Acadia,Louisiana,US,2020-04-03 22:46:37,30.295065,-92.414197,72,1,0,0,"Acadia, Louisiana, US",2016-07-01
2,51001.0,Accomack,Virginia,US,2020-04-03 22:46:37,37.767072,-75.632346,8,0,0,0,"Accomack, Virginia, US",2019-01-01
3,16001.0,Ada,Idaho,US,2020-04-03 22:46:37,43.452658,-116.241552,307,3,0,0,"Ada, Idaho, US",2020-01-01
4,19001.0,Adair,Iowa,US,2020-04-03 22:46:37,41.330756,-94.471059,1,0,0,0,"Adair, Iowa, US",2014-01-01
5,29001.0,Adair,Missouri,US,2020-04-03 22:46:37,40.190586,-92.600782,6,0,0,0,"Adair, Missouri, US",NaT
6,40001.0,Adair,Oklahoma,US,2020-04-03 22:46:37,35.884942,-94.658593,14,0,0,0,"Adair, Oklahoma, US",NaT
7,8001.0,Adams,Colorado,US,2020-04-03 22:46:37,39.874321,-104.336258,260,7,0,0,"Adams, Colorado, US",2014-01-01
8,16003.0,Adams,Idaho,US,2020-04-03 22:46:37,44.893336,-116.454525,1,0,0,0,"Adams, Idaho, US",2020-01-01
9,17001.0,Adams,Illinois,US,2020-04-03 22:46:37,39.988156,-91.187868,2,0,0,0,"Adams, Illinois, US",2014-01-01
10,18001.0,Adams,Indiana,US,2020-04-03 22:46:37,40.745765,-84.936714,1,0,0,0,"Adams, Indiana, US",2015-02-01
11,28001.0,Adams,Mississippi,US,2020-04-03 22:46:37,31.476698,-91.353260,14,0,0,0,"Adams, Mississippi, US",NaT
12,31001.0,Adams,Nebraska,US,2020-04-03 22:46:37,40.524494,-98.501178,6,0,0,0,"Adams, Nebraska, US",NaT
13,42001.0,Adams,Pennsylvania,US,2020-04-03 22:46:37,39.871404,-77.216103,19,0,0,0,"Adams, Pennsylvania, US",2015-01-01
14,53001.0,Adams,Washington,US,2020-04-03 22:46:37,46.982998,-118.560173,20,0,0,0,"Adams, Washington, US",2014-01-01
15,55001.0,Adams,Wisconsin,US,2020-04-03 22:46:37,43.969747,-89.767828,1,0,0,0,"Adams, Wisconsin, US",NaT
16,50001.0,Addison,Vermont,US,2020-04-03 22:46:37,44.032173,-73.141309,32,0,0,0,"Addison, Vermont, US",2014-01-01
17,45003.0,Aiken,South Carolina,US,2020-04-03 22:46:37,33.543380,-81.636454,22,1,0,0,"Aiken, South Carolina, US",NaT
18,12001.0,Alachua,Florida,US,2020-04-03 22:46:37,29.678665,-82.359282,110,0,0,0,"Alachua, Florida, US",NaT
19,37001.0,Alamance,North Carolina,US,2020-04-03 22:46:37,36.043470,-79.399761,14,0,0,0,"Alamance, North Carolina, US",NaT
20,6001.0,Alameda,California,US,2020-04-03 22:46:37,37.646294,-121.892927,443,12,0,0,"Alameda, California, US",2014-01-01
21,8003.0,Alamosa,Colorado,US,2020-04-03 22:46:37,37.572506,-105.788545,4,0,0,0,"Alamosa, Colorado, US",2014-01-01
22,36001.0,Albany,New York,US,2020-04-03 22:46:37,42.600603,-73.977239,267,2,0,0,"Albany, New York, US",2014-01-01
23,56001.0,Albany,Wyoming,US,2020-04-03 22:46:37,41.654987,-105.723541,4,0,0,0,"Albany, Wyoming, US",NaT
24,51003.0,Albemarle,Virginia,US,2020-04-03 22:46:37,38.020807,-78.554811,26,0,0,0,"Albemarle, Virginia, US",2019-01-01
25,28003.0,Alcorn,Mississippi,US,2020-04-03 22:46:37,34.880845,-88.579962,6,0,0,0,"Alcorn, Mississippi, US",NaT
26,37003.0,Alexander,North Carolina,US,2020-04-03 22:46:37,35.922380,-81.177519,2,0,0,0,"Alexander, North Carolina, US",NaT
27,51510.0,Alexandria,Virginia,US,2020-04-03 22:46:37,38.814003,-77.081831,56,0,0,0,"Alexandria, Virginia, US",2019-01-01
28,19005.0,Allamakee,Iowa,US,2020-04-03 22:46:37,43.283832,-91.378609,16,1,0,0,"Allamakee, Iowa, US",2014-01-01
29,26005.0,Allegan,Michigan,US,2020-04-03 22:46:37,42.591470,-85.891029,6,0,0,0,"Allegan, Michigan, US",2014-04-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2338,51197.0,Wythe,Virginia,US,2020-04-03 22:46:37,36.915820,-81.078341,2,0,0,0,"Wythe, Virginia, US",2019-01-01
2339,37197.0,Yadkin,North Carolina,US,2020-04-03 22:46:37,36.162226,-80.662394,6,0,0,0,"Yadkin, North Carolina, US",NaT
2340,53077.0,Yakima,Washington,US,2020-04-03 22:46:37,46.457385,-120.738013,240,6,0,0,"Yakima, Washington, US",2014-01-01
2341,28161.0,Yalobusha,Mississippi,US,2020-04-03 22:46:37,34.028242,-89.707620,7,0,0,0,"Yalobusha, Mississippi, US",NaT
2342,41071.0,Yamhill,Oregon,US,2020-04-03 22:46:37,45.233304,-123.308696,23,3,0,0,"Yamhill, Oregon, US",2014-01-01
2343,46135.0,Yankton,South Dakota,US,2020-04-03 22:46:37,43.009245,-97.394676,11,0,0,0,"Yankton, South Dakota, US",NaT
2344,36123.0,Yates,New York,US,2020-04-03 22:46:37,42.635055,-77.103699,1,0,0,0,"Yates, New York, US",2014-01-01
2345,4025.0,Yavapai,Arizona,US,2020-04-03 22:46:37,34.599339,-112.553859,35,0,0,0,"Yavapai, Arizona, US",2014-01-01
2346,28163.0,Yazoo,Mississippi,US,2020-04-03 22:46:37,32.778904,-90.396561,13,1,0,0,"Yazoo, Mississippi, US",NaT
2347,27173.0,Yellow Medicine,Minnesota,US,2020-04-03 22:46:37,44.717102,-95.868425,1,0,0,0,"Yellow Medicine, Minnesota, US",2014-01-01
2348,30111.0,Yellowstone,Montana,US,2020-04-03 22:46:37,45.939559,-108.269149,36,0,0,0,"Yellowstone, Montana, US",2016-01-01
2349,6113.0,Yolo,California,US,2020-04-03 22:46:37,38.682789,-121.901829,33,1,0,0,"Yolo, California, US",2014-01-01
2350,23031.0,York,Maine,US,2020-04-03 22:46:37,43.478084,-70.710524,89,1,0,0,"York, Maine, US",2019-01-10
2351,31185.0,York,Nebraska,US,2020-04-03 22:46:37,40.872726,-97.597102,1,0,0,0,"York, Nebraska, US",NaT
2352,42133.0,York,Pennsylvania,US,2020-04-03 22:46:37,39.921009,-76.730401,121,1,0,0,"York, Pennsylvania, US",2015-01-01
2353,45091.0,York,South Carolina,US,2020-04-03 22:46:37,34.972815,-81.180859,73,1,0,0,"York, South Carolina, US",NaT
2354,51199.0,York,Virginia,US,2020-04-03 22:46:37,37.243748,-76.544128,17,1,0,0,"York, Virginia, US",2019-01-01
2355,48503.0,Young,Texas,US,2020-04-03 22:46:37,33.176597,-98.687909,3,0,0,0,"Young, Texas, US",NaT
2356,6115.0,Yuba,California,US,2020-04-03 22:46:37,39.262559,-121.353564,8,0,0,0,"Yuba, California, US",2014-01-01
2357,2290.0,Yukon-Koyukuk,Alaska,US,2020-04-03 22:46:37,65.508155,-151.390739,1,0,0,0,"Yukon-Koyukuk, Alaska, US",2015-09-01
2358,4027.0,Yuma,Arizona,US,2020-04-03 22:46:37,32.768957,-113.906667,13,0,0,0,"Yuma, Arizona, US",2014-01-01
2359,8125.0,Yuma,Colorado,US,2020-04-03 22:46:37,40.003468,-102.425867,2,0,0,0,"Yuma, Colorado, US",2014-01-01
2360,88888.0,NaN,Diamond Princess,US,2020-04-03 22:46:37,NaN,NaN,49,0,0,0,"Diamond Princess, US",NaT
2361,99999.0,NaN,Grand Princess,US,2020-04-03 22:46:37,NaN,NaN,103,3,0,0,"Grand Princess, US",NaT
2362,66.0,NaN,Guam,US,2020-04-03 22:46:37,13.444300,144.793700,84,4,0,0,"Guam, US",NaT
2363,NaN,NaN,Northern Mariana Islands,US,2020-04-03 22:46:37,15.097900,145.673900,6,1,0,0,",Northern Mariana Islands,US",NaT
2364,72.0,NaN,Puerto Rico,US,2020-04-03 22:46:37,18.220800,-66.590100,316,15,0,0,"Puerto Rico, US",NaT
2365,NaN,NaN,Recovered,US,2020-04-03 22:46:37,NaN,NaN,0,0,9707,0,"Recovered, US",NaT
2366,78.0,NaN,Virgin Islands,US,2020-04-03 22:46:37,18.335800,-64.896300,37,0,0,0,",Virgin Islands,US",NaT
2367,NaN,unassigned,Wyoming,US,2020-04-03 22:46:37,NaN,NaN,0,0,0,0,"unassigned, Wyoming, US",NaT

In [15]:
import numpy as np
usaMedicaid['Is_Medicaid'] = ['NoMedicaid' if pd.isnull(impdt) else 'Medicaid' for impdt in usaMedicaid['Implemented_Dt']]

In [16]:
usaMedicaid

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Implemented_Dt,Is_Medicaid
0,45001.0,Abbeville,South Carolina,US,2020-04-03 22:46:37,34.223334,-82.461707,6,0,0,0,"Abbeville, South Carolina, US",NaT,NoMedicaid
1,22001.0,Acadia,Louisiana,US,2020-04-03 22:46:37,30.295065,-92.414197,72,1,0,0,"Acadia, Louisiana, US",2016-07-01,Medicaid
2,51001.0,Accomack,Virginia,US,2020-04-03 22:46:37,37.767072,-75.632346,8,0,0,0,"Accomack, Virginia, US",2019-01-01,Medicaid
3,16001.0,Ada,Idaho,US,2020-04-03 22:46:37,43.452658,-116.241552,307,3,0,0,"Ada, Idaho, US",2020-01-01,Medicaid
4,19001.0,Adair,Iowa,US,2020-04-03 22:46:37,41.330756,-94.471059,1,0,0,0,"Adair, Iowa, US",2014-01-01,Medicaid
5,29001.0,Adair,Missouri,US,2020-04-03 22:46:37,40.190586,-92.600782,6,0,0,0,"Adair, Missouri, US",NaT,NoMedicaid
6,40001.0,Adair,Oklahoma,US,2020-04-03 22:46:37,35.884942,-94.658593,14,0,0,0,"Adair, Oklahoma, US",NaT,NoMedicaid
7,8001.0,Adams,Colorado,US,2020-04-03 22:46:37,39.874321,-104.336258,260,7,0,0,"Adams, Colorado, US",2014-01-01,Medicaid
8,16003.0,Adams,Idaho,US,2020-04-03 22:46:37,44.893336,-116.454525,1,0,0,0,"Adams, Idaho, US",2020-01-01,Medicaid
9,17001.0,Adams,Illinois,US,2020-04-03 22:46:37,39.988156,-91.187868,2,0,0,0,"Adams, Illinois, US",2014-01-01,Medicaid
10,18001.0,Adams,Indiana,US,2020-04-03 22:46:37,40.745765,-84.936714,1,0,0,0,"Adams, Indiana, US",2015-02-01,Medicaid
11,28001.0,Adams,Mississippi,US,2020-04-03 22:46:37,31.476698,-91.353260,14,0,0,0,"Adams, Mississippi, US",NaT,NoMedicaid
12,31001.0,Adams,Nebraska,US,2020-04-03 22:46:37,40.524494,-98.501178,6,0,0,0,"Adams, Nebraska, US",NaT,NoMedicaid
13,42001.0,Adams,Pennsylvania,US,2020-04-03 22:46:37,39.871404,-77.216103,19,0,0,0,"Adams, Pennsylvania, US",2015-01-01,Medicaid
14,53001.0,Adams,Washington,US,2020-04-03 22:46:37,46.982998,-118.560173,20,0,0,0,"Adams, Washington, US",2014-01-01,Medicaid
15,55001.0,Adams,Wisconsin,US,2020-04-03 22:46:37,43.969747,-89.767828,1,0,0,0,"Adams, Wisconsin, US",NaT,NoMedicaid
16,50001.0,Addison,Vermont,US,2020-04-03 22:46:37,44.032173,-73.141309,32,0,0,0,"Addison, Vermont, US",2014-01-01,Medicaid
17,45003.0,Aiken,South Carolina,US,2020-04-03 22:46:37,33.543380,-81.636454,22,1,0,0,"Aiken, South Carolina, US",NaT,NoMedicaid
18,12001.0,Alachua,Florida,US,2020-04-03 22:46:37,29.678665,-82.359282,110,0,0,0,"Alachua, Florida, US",NaT,NoMedicaid
19,37001.0,Alamance,North Carolina,US,2020-04-03 22:46:37,36.043470,-79.399761,14,0,0,0,"Alamance, North Carolina, US",NaT,NoMedicaid
20,6001.0,Alameda,California,US,2020-04-03 22:46:37,37.646294,-121.892927,443,12,0,0,"Alameda, California, US",2014-01-01,Medicaid
21,8003.0,Alamosa,Colorado,US,2020-04-03 22:46:37,37.572506,-105.788545,4,0,0,0,"Alamosa, Colorado, US",2014-01-01,Medicaid
22,36001.0,Albany,New York,US,2020-04-03 22:46:37,42.600603,-73.977239,267,2,0,0,"Albany, New York, US",2014-01-01,Medicaid
23,56001.0,Albany,Wyoming,US,2020-04-03 22:46:37,41.654987,-105.723541,4,0,0,0,"Albany, Wyoming, US",NaT,NoMedicaid
24,51003.0,Albemarle,Virginia,US,2020-04-03 22:46:37,38.020807,-78.554811,26,0,0,0,"Albemarle, Virginia, US",2019-01-01,Medicaid
25,28003.0,Alcorn,Mississippi,US,2020-04-03 22:46:37,34.880845,-88.579962,6,0,0,0,"Alcorn, Mississippi, US",NaT,NoMedicaid
26,37003.0,Alexander,North Carolina,US,2020-04-03 22:46:37,35.922380,-81.177519,2,0,0,0,"Alexander, North Carolina, US",NaT,NoMedicaid
27,51510.0,Alexandria,Virginia,US,2020-04-03 22:46:37,38.814003,-77.081831,56,0,0,0,"Alexandria, Virginia, US",2019-01-01,Medicaid
28,19005.0,Allamakee,Iowa,US,2020-04-03 22:46:37,43.283832,-91.378609,16,1,0,0,"Allamakee, Iowa, US",2014-01-01,Medicaid
29,26005.0,Allegan,Michigan,US,2020-04-03 22:46:37,42.591470,-85.891029,6,0,0,0,"Allegan, Michigan, US",2014-04-01,Medicaid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2338,51197.0,Wythe,Virginia,US,2020-04-03 22:46:37,36.915820,-81.078341,2,0,0,0,"Wythe, Virginia, US",2019-01-01,Medicaid
2339,37197.0,Yadkin,North Carolina,US,2020-04-03 22:46:37,36.162226,-80.662394,6,0,0,0,"Yadkin, North Carolina, US",NaT,NoMedicaid
2340,53077.0,Yakima,Washington,US,2020-04-03 22:46:37,46.457385,-120.738013,240,6,0,0,"Yakima, Washington, US",2014-01-01,Medicaid
2341,28161.0,Yalobusha,Mississippi,US,2020-04-03 22:46:37,34.028242,-89.707620,7,0,0,0,"Yalobusha, Mississippi, US",NaT,NoMedicaid
2342,41071.0,Yamhill,Oregon,US,2020-04-03 22:46:37,45.233304,-123.308696,23,3,0,0,"Yamhill, Oregon, US",2014-01-01,Medicaid
2343,46135.0,Yankton,South Dakota,US,2020-04-03 22:46:37,43.009245,-97.394676,11,0,0,0,"Yankton, South Dakota, US",NaT,NoMedicaid
2344,36123.0,Yates,New York,US,2020-04-03 22:46:37,42.635055,-77.103699,1,0,0,0,"Yates, New York, US",2014-01-01,Medicaid
2345,4025.0,Yavapai,Arizona,US,2020-04-03 22:46:37,34.599339,-112.553859,35,0,0,0,"Yavapai, Arizona, US",2014-01-01,Medicaid
2346,28163.0,Yazoo,Mississippi,US,2020-04-03 22:46:37,32.778904,-90.396561,13,1,0,0,"Yazoo, Mississippi, US",NaT,NoMedicaid
2347,27173.0,Yellow Medicine,Minnesota,US,2020-04-03 22:46:37,44.717102,-95.868425,1,0,0,0,"Yellow Medicine, Minnesota, US",2014-01-01,Medicaid
2348,30111.0,Yellowstone,Montana,US,2020-04-03 22:46:37,45.939559,-108.269149,36,0,0,0,"Yellowstone, Montana, US",2016-01-01,Medicaid
2349,6113.0,Yolo,California,US,2020-04-03 22:46:37,38.682789,-121.901829,33,1,0,0,"Yolo, California, US",2014-01-01,Medicaid
2350,23031.0,York,Maine,US,2020-04-03 22:46:37,43.478084,-70.710524,89,1,0,0,"York, Maine, US",2019-01-10,Medicaid
2351,31185.0,York,Nebraska,US,2020-04-03 22:46:37,40.872726,-97.597102,1,0,0,0,"York, Nebraska, US",NaT,NoMedicaid
2352,42133.0,York,Pennsylvania,US,2020-04-03 22:46:37,39.921009,-76.730401,121,1,0,0,"York, Pennsylvania, US",2015-01-01,Medicaid
2353,45091.0,York,South Carolina,US,2020-04-03 22:46:37,34.972815,-81.180859,73,1,0,0,"York, South Carolina, US",NaT,NoMedicaid
2354,51199.0,York,Virginia,US,2020-04-03 22:46:37,37.243748,-76.544128,17,1,0,0,"York, Virginia, US",2019-01-01,Medicaid
2355,48503.0,Young,Texas,US,2020-04-03 22:46:37,33.176597,-98.687909,3,0,0,0,"Young, Texas, US",NaT,NoMedicaid
2356,6115.0,Yuba,California,US,2020-04-03 22:46:37,39.262559,-121.353564,8,0,0,0,"Yuba, California, US",2014-01-01,Medicaid
2357,2290.0,Yukon-Koyukuk,Alaska,US,2020-04-03 22:46:37,65.508155,-151.390739,1,0,0,0,"Yukon-Koyukuk, Alaska, US",2015-09-01,Medicaid
2358,4027.0,Yuma,Arizona,US,2020-04-03 22:46:37,32.768957,-113.906667,13,0,0,0,"Yuma, Arizona, US",2014-01-01,Medicaid
2359,8125.0,Yuma,Colorado,US,2020-04-03 22:46:37,40.003468,-102.425867,2,0,0,0,"Yuma, Colorado, US",2014-01-01,Medicaid
2360,88888.0,NaN,Diamond Princess,US,2020-04-03 22:46:37,NaN,NaN,49,0,0,0,"Diamond Princess, US",NaT,NoMedicaid
2361,99999.0,NaN,Grand Princess,US,2020-04-03 22:46:37,NaN,NaN,103,3,0,0,"Grand Princess, US",NaT,NoMedicaid
2362,66.0,NaN,Guam,US,2020-04-03 22:46:37,13.444300,144.793700,84,4,0,0,"Guam, US",NaT,NoMedicaid
2363,NaN,NaN,Northern Mariana Islands,US,2020-04-03 22:46:37,15.097900,145.673900,6,1,0,0,",Northern Mariana Islands,US",NaT,NoMedicaid
2364,72.0,NaN,Puerto Rico,US,2020-04-03 22:46:37,18.220800,-66.590100,316,15,0,0,"Puerto Rico, US",NaT,NoMedicaid
2365,NaN,NaN,Recovered,US,2020-04-03 22:46:37,NaN,NaN,0,0,9707,0,"Recovered, US",NaT,NoMedicaid
2366,78.0,NaN,Virgin Islands,US,2020-04-03 22:46:37,18.335800,-64.896300,37,0,0,0,",Virgin Islands,US",NaT,NoMedicaid
2367,NaN,unassigned,Wyoming,US,2020-04-03 22:46:37,NaN,NaN,0,0,0,0,"unassigned, Wyoming, US",NaT,NoMedicaid

In [134]:
#4/2
wMedicaidConf = usaMedicaid.groupby(['Province_State','Is_Medicaid'])['Confirmed','Deaths'].sum()
wMedicaidConf

                                      Confirmed  Deaths
Province_State           Is_Medicaid
Alabama                  NoMedicaid        1233      32
Alaska                   Medicaid           143       3
Arizona                  Medicaid          1715      32
Arkansas                 Medicaid           643      12
California               Medicaid         10773     238
Colorado                 Medicaid          3342      80
Connecticut              Medicaid          3824     112
Delaware                 Medicaid           393      12
Diamond Princess         NoMedicaid          49       0
District of Columbia     Medicaid           653      12
Florida                  NoMedicaid        9008     164
Georgia                  NoMedicaid        5348     163
Grand Princess           NoMedicaid         103       3
Guam                     NoMedicaid          82       3
Hawaii                   Medicaid           256       1
Idaho                    Medicaid           776       9
Illinois                 Medicaid          7695     163
Indiana                  Medicaid          3038      78
Iowa                     Medicaid           614      11
Kansas                   NoMedicaid         553      12
Kentucky                 Medicaid           770      31
Louisiana                Medicaid          9159     310
Maine                    Medicaid           376       7
Maryland                 Medicaid          2331      36
Massachusetts            Medicaid          8966     154
Michigan                 Medicaid         10791     417
Minnesota                Medicaid           742      18
Mississippi              NoMedicaid        1177      26
Missouri                 NoMedicaid        1857      22
Montana                  Medicaid           241       6
Nebraska                 NoMedicaid         246       5
Nevada                   Medicaid          1463      38
New Hampshire            Medicaid           316       3
New Jersey               Medicaid         25590     537
New Mexico               Medicaid           388       6
New York                 Medicaid         92506    2373
North Carolina           NoMedicaid        1977      21
North Dakota             Medicaid           159       3
Northern Mariana Islands NoMedicaid           6       1
Ohio                     Medicaid          2901      81
Oklahoma                 NoMedicaid         881      34
Oregon                   Medicaid           826      21
Pennsylvania             Medicaid          7268      90
Puerto Rico              NoMedicaid         316      12
Recovered                NoMedicaid           0       0
Rhode Island             Medicaid           657      12
South Carolina           NoMedicaid        1554      31
South Dakota             NoMedicaid         165       2
Tennessee                NoMedicaid        2845      36
Texas                    NoMedicaid        5069      77
Utah                     Medicaid          1092       7
Vermont                  Medicaid           338      17
Virgin Islands           NoMedicaid          30       0
Virginia                 Medicaid          1706      41
Washington               Medicaid          6389     271
West Virginia            Medicaid           216       2
Wisconsin                NoMedicaid        1748      38
Wyoming                  NoMedicaid         150       0

In [17]:
#4/3
wMedicaidConf = usaMedicaid.groupby(['Province_State','Is_Medicaid'])['Confirmed','Deaths'].sum()
wMedicaidConf

                                      Confirmed  Deaths
Province_State           Is_Medicaid
Alabama                  NoMedicaid        1495      38
Alaska                   Medicaid           157       3
Arizona                  Medicaid          1937      41
Arkansas                 Medicaid           704      12
California               Medicaid         12004     265
Colorado                 Medicaid          3742      97
Connecticut              Medicaid          4914     131
Delaware                 Medicaid           450      14
Diamond Princess         NoMedicaid          49       0
District of Columbia     Medicaid           757      15
Florida                  NoMedicaid       10268     170
Georgia                  NoMedicaid        5831     184
Grand Princess           NoMedicaid         103       3
Guam                     NoMedicaid          84       4
Hawaii                   Medicaid           319       3
Idaho                    Medicaid           891       9
Illinois                 Medicaid          8904     210
Indiana                  Medicaid          3437     102
Iowa                     Medicaid           699      11
Kansas                   NoMedicaid         629      18
Kentucky                 Medicaid           770      34
Louisiana                Medicaid         10297     370
Maine                    Medicaid           432       9
Maryland                 Medicaid          2758      43
Massachusetts            Medicaid         10402     192
Michigan                 Medicaid         12744     479
Minnesota                Medicaid           788      22
Mississippi              NoMedicaid        1358      29
Missouri                 NoMedicaid        1864      25
Montana                  Medicaid           243       5
Nebraska                 NoMedicaid         279       6
Nevada                   Medicaid          1514      43
New Hampshire            Medicaid           479       5
New Jersey               Medicaid         29895     646
New Mexico               Medicaid           534      10
New York                 Medicaid        102987    2935
North Carolina           NoMedicaid        2251      27
North Dakota             Medicaid           173       3
Northern Mariana Islands NoMedicaid           8       1
Ohio                     Medicaid          3312      91
Oklahoma                 NoMedicaid         990      38
Oregon                   Medicaid           899      22
Pennsylvania             Medicaid          8570     102
Puerto Rico              NoMedicaid         316      15
Recovered                NoMedicaid           0       0
Rhode Island             Medicaid           711      14
South Carolina           NoMedicaid        1700      34
South Dakota             NoMedicaid         187       2
Tennessee                NoMedicaid        3067      41
Texas                    NoMedicaid        5734     100
Utah                     Medicaid          1255       7
Vermont                  Medicaid           389      17
Virgin Islands           NoMedicaid          37       0
Virginia                 Medicaid          2012      46
Washington               Medicaid          6846     291
West Virginia            Medicaid           237       2
Wisconsin                NoMedicaid        2012      51
Wyoming                  NoMedicaid         162       0

In [135]:
#4/2
wMedicaidConfOver1k = wMedicaidConf[wMedicaidConf['Confirmed'] > 1000]
wMedicaidConfOver1k

                            Confirmed  Deaths
Province_State Is_Medicaid
Alabama        NoMedicaid        1233      32
Arizona        Medicaid          1715      32
California     Medicaid         10773     238
Colorado       Medicaid          3342      80
Connecticut    Medicaid          3824     112
Florida        NoMedicaid        9008     164
Georgia        NoMedicaid        5348     163
Illinois       Medicaid          7695     163
Indiana        Medicaid          3038      78
Louisiana      Medicaid          9159     310
Maryland       Medicaid          2331      36
Massachusetts  Medicaid          8966     154
Michigan       Medicaid         10791     417
Mississippi    NoMedicaid        1177      26
Missouri       NoMedicaid        1857      22
Nevada         Medicaid          1463      38
New Jersey     Medicaid         25590     537
New York       Medicaid         92506    2373
North Carolina NoMedicaid        1977      21
Ohio           Medicaid          2901      81
Pennsylvania   Medicaid          7268      90
South Carolina NoMedicaid        1554      31
Tennessee      NoMedicaid        2845      36
Texas          NoMedicaid        5069      77
Utah           Medicaid          1092       7
Virginia       Medicaid          1706      41
Washington     Medicaid          6389     271
Wisconsin      NoMedicaid        1748      38

In [19]:
#4/3
wMedicaidConfOver1k = wMedicaidConf[wMedicaidConf['Confirmed'] > 1000]
wMedicaidConfOver1k

                            Confirmed  Deaths
Province_State Is_Medicaid
Alabama        NoMedicaid        1495      38
Arizona        Medicaid          1937      41
California     Medicaid         12004     265
Colorado       Medicaid          3742      97
Connecticut    Medicaid          4914     131
Florida        NoMedicaid       10268     170
Georgia        NoMedicaid        5831     184
Illinois       Medicaid          8904     210
Indiana        Medicaid          3437     102
Louisiana      Medicaid         10297     370
Maryland       Medicaid          2758      43
Massachusetts  Medicaid         10402     192
Michigan       Medicaid         12744     479
Mississippi    NoMedicaid        1358      29
Missouri       NoMedicaid        1864      25
Nevada         Medicaid          1514      43
New Jersey     Medicaid         29895     646
New York       Medicaid        102987    2935
North Carolina NoMedicaid        2251      27
Ohio           Medicaid          3312      91
Pennsylvania   Medicaid          8570     102
South Carolina NoMedicaid        1700      34
Tennessee      NoMedicaid        3067      41
Texas          NoMedicaid        5734     100
Utah           Medicaid          1255       7
Virginia       Medicaid          2012      46
Washington     Medicaid          6846     291
Wisconsin      NoMedicaid        2012      51

In [18]:
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="ticks", color_codes=True)

In [137]:
#4/2
wMedicaidConfOver1k['Mortality'] = wMedicaidConfOver1k['Deaths'] / wMedicaidConfOver1k['Confirmed'] * 100
wMedicaidConfOver1k

/Users/dineshmurali/miniconda3/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

                            Confirmed  Deaths  Mortality
Province_State Is_Medicaid
Alabama        NoMedicaid        1233      32   2.595296
Arizona        Medicaid          1715      32   1.865889
California     Medicaid         10773     238   2.209227
Colorado       Medicaid          3342      80   2.393776
Connecticut    Medicaid          3824     112   2.928870
Florida        NoMedicaid        9008     164   1.820604
Georgia        NoMedicaid        5348     163   3.047868
Illinois       Medicaid          7695     163   2.118259
Indiana        Medicaid          3038      78   2.567479
Louisiana      Medicaid          9159     310   3.384649
Maryland       Medicaid          2331      36   1.544402
Massachusetts  Medicaid          8966     154   1.717600
Michigan       Medicaid         10791     417   3.864331
Mississippi    NoMedicaid        1177      26   2.209006
Missouri       NoMedicaid        1857      22   1.184707
Nevada         Medicaid          1463      38   2.597403
New Jersey     Medicaid         25590     537   2.098476
New York       Medicaid         92506    2373   2.565239
North Carolina NoMedicaid        1977      21   1.062215
Ohio           Medicaid          2901      81   2.792141
Pennsylvania   Medicaid          7268      90   1.238305
South Carolina NoMedicaid        1554      31   1.994852
Tennessee      NoMedicaid        2845      36   1.265378
Texas          NoMedicaid        5069      77   1.519037
Utah           Medicaid          1092       7   0.641026
Virginia       Medicaid          1706      41   2.403283
Washington     Medicaid          6389     271   4.241665
Wisconsin      NoMedicaid        1748      38   2.173913

In [20]:
#4/3
wMedicaidConfOver1k['Mortality'] = wMedicaidConfOver1k['Deaths'] / wMedicaidConfOver1k['Confirmed'] * 100
wMedicaidConfOver1k

/Users/dineshmurali/miniconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

                            Confirmed  Deaths  Mortality
Province_State Is_Medicaid
Alabama        NoMedicaid        1495      38   2.541806
Arizona        Medicaid          1937      41   2.116675
California     Medicaid         12004     265   2.207597
Colorado       Medicaid          3742      97   2.592197
Connecticut    Medicaid          4914     131   2.665853
Florida        NoMedicaid       10268     170   1.655629
Georgia        NoMedicaid        5831     184   3.155548
Illinois       Medicaid          8904     210   2.358491
Indiana        Medicaid          3437     102   2.967704
Louisiana      Medicaid         10297     370   3.593280
Maryland       Medicaid          2758      43   1.559101
Massachusetts  Medicaid         10402     192   1.845799
Michigan       Medicaid         12744     479   3.758632
Mississippi    NoMedicaid        1358      29   2.135493
Missouri       NoMedicaid        1864      25   1.341202
Nevada         Medicaid          1514      43   2.840159
New Jersey     Medicaid         29895     646   2.160896
New York       Medicaid        102987    2935   2.849874
North Carolina NoMedicaid        2251      27   1.199467
Ohio           Medicaid          3312      91   2.747585
Pennsylvania   Medicaid          8570     102   1.190198
South Carolina NoMedicaid        1700      34   2.000000
Tennessee      NoMedicaid        3067      41   1.336811
Texas          NoMedicaid        5734     100   1.743983
Utah           Medicaid          1255       7   0.557769
Virginia       Medicaid          2012      46   2.286282
Washington     Medicaid          6846     291   4.250657
Wisconsin      NoMedicaid        2012      51   2.534791

In [138]:
wMedicaidConfOver1k = wMedicaidConfOver1k.reset_index()
wMedicaidConfOver1k

    Province_State Is_Medicaid  Confirmed  Deaths  Mortality
0          Alabama  NoMedicaid       1233      32   2.595296
1          Arizona    Medicaid       1715      32   1.865889
2       California    Medicaid      10773     238   2.209227
3         Colorado    Medicaid       3342      80   2.393776
4      Connecticut    Medicaid       3824     112   2.928870
5          Florida  NoMedicaid       9008     164   1.820604
6          Georgia  NoMedicaid       5348     163   3.047868
7         Illinois    Medicaid       7695     163   2.118259
8          Indiana    Medicaid       3038      78   2.567479
9        Louisiana    Medicaid       9159     310   3.384649
10        Maryland    Medicaid       2331      36   1.544402
11   Massachusetts    Medicaid       8966     154   1.717600
12        Michigan    Medicaid      10791     417   3.864331
13     Mississippi  NoMedicaid       1177      26   2.209006
14        Missouri  NoMedicaid       1857      22   1.184707
15          Nevada    Medicaid       1463      38   2.597403
16      New Jersey    Medicaid      25590     537   2.098476
17        New York    Medicaid      92506    2373   2.565239
18  North Carolina  NoMedicaid       1977      21   1.062215
19            Ohio    Medicaid       2901      81   2.792141
20    Pennsylvania    Medicaid       7268      90   1.238305
21  South Carolina  NoMedicaid       1554      31   1.994852
22       Tennessee  NoMedicaid       2845      36   1.265378
23           Texas  NoMedicaid       5069      77   1.519037
24            Utah    Medicaid       1092       7   0.641026
25        Virginia    Medicaid       1706      41   2.403283
26      Washington    Medicaid       6389     271   4.241665
27       Wisconsin  NoMedicaid       1748      38   2.173913

In [140]:
mortByMedi = wMedicaidConfOver1k.groupby('Is_Medicaid')['Mortality'].mean()
mortByMedi

Is_Medicaid
Medicaid      2.398445
NoMedicaid    1.887288
Name: Mortality, dtype: float64